# Generated by Django 4.1.1 on 2023-01-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_panel_panelcarousel_productcategory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcarousel',
            name='panel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.panel'),
            preserve_default=False,
        ),
    ]
