# Generated by Django 4.1.1 on 2023-01-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_panelcarousel_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcarousel',
            name='autoplay',
            field=models.BooleanField(default=True, verbose_name='Autoplay'),
        ),
    ]
