# Generated by Django 4.1.1 on 2023-01-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_panelcarousel_autoplay_panel_autoplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.CharField(max_length=250, verbose_name='Catalè')),
                ('es', models.CharField(max_length=250, verbose_name='Castellano')),
            ],
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ('order',)},
        ),
    ]
