# Generated by Django 4.1.1 on 2023-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_translate_alter_panel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='about_us',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre nosaltres'),
        ),
        migrations.AddField(
            model_name='config',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Direcció'),
        ),
        migrations.AddField(
            model_name='config',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Telèfon'),
        ),
        migrations.AddField(
            model_name='config',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telèfon'),
        ),
    ]
