# Generated by Django 4.1.1 on 2023-01-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_config_about_us_config_address_config_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcarousel',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', verbose_name='Imatge per mòbil'),
        ),
        migrations.AlterField(
            model_name='config',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Correu electrònic'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='type',
            field=models.IntegerField(choices=[(1, 'CAROUSEL'), (2, 'PRODUCT CATEGORY'), (3, 'PRODUCT'), (4, 'CAROUSEL DE PRODUCTES')], default=1, verbose_name='Tipus de panell'),
        ),
    ]
