# Generated by Django 4.2.5 on 2024-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_panelcarousel_image_mobile_alter_config_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='ca',
            field=models.TextField(verbose_name='Català'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='es',
            field=models.TextField(verbose_name='Castellano'),
        ),
    ]
