# Generated by Django 4.2.5 on 2024-04-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_translate_ca_alter_translate_es'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='type',
            field=models.IntegerField(choices=[(1, 'CAROUSEL'), (2, 'PRODUCT CATEGORY'), (3, 'PRODUCT'), (4, 'CAROUSEL DE PRODUCTES'), (5, 'JUMBOTRON')], default=1, verbose_name='Tipus de panell'),
        ),
        migrations.CreateModel(
            name='PanelJumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Títol')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripció')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enllaç')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.panel')),
            ],
        ),
    ]
