# Generated by Django 5.1.7 on 2025-04-21 14:45

from django.db import migrations

def create_initial_record(apps, schema_editor):
    MyModel = apps.get_model('store', 'Config')
    MyModel.objects.create(
        name='Company Name',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_panel_type_paneljumbotron'),
    ]

    operations = [
        migrations.RunPython(create_initial_record),
    ]
