# Generated by Django 5.1.7 on 2025-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20250421_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
    ]
