# Generated by Django 5.1.7 on 2025-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_panel_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nom del panell'),
            preserve_default=False,
        ),
    ]
