# Generated by Django 4.1.1 on 2023-01-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(choices=[('ca-es', 'Català'), ('es-es', 'Español')], default='ca-es', max_length=5, verbose_name='language'),
        ),
    ]
