# Generated by Django 4.2.5 on 2024-04-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_myuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Español')], default='ca', max_length=5, verbose_name='language'),
        ),
    ]
